In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#  1. read csv file and print 1st 5 rows
df = pd.read_csv('diamonds.csv')
df.head()

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75

In [3]:
# 2. print first 6
df.head(6)
df.rename(columns={'cut': 'Quality'})

,Unnamed: 0,carat,Quality,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [4]:
# 3. select a series from dataframe and print contents of it
df['color']

0        E
1        E
2        E
3        I
4        J
        ..
53935    D
53936    D
53937    D
53938    H
53939    D
Name: color, Length: 53940, dtype: object

In [5]:
# 4. create a new 'Quality-color' Series
df['Quality-color'] = df.cut + ', ' + df.color

In [6]:
df

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z,Quality-color
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,"Ideal, E"
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,"Premium, E"
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,"Good, E"
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,"Premium, I"
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,"Good, J"
...,...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,"Ideal, D"
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,"Good, D"
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,"Very Good, D"
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,"Premium, H"
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,"Ideal, D"

In [7]:
# 5. number of rows and columns
df.shape

(53940, 12)

In [8]:
# 5. type of each column
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     53940 non-null  int64
 1   carat          53940 non-null  float64
 2   cut            53940 non-null  object
 3   color          53940 non-null  object
 4   clarity        53940 non-null  object
 5   depth          53940 non-null  float64
 6   table          53940 non-null  float64
 7   price          53940 non-null  int64
 8   x              53940 non-null  float64
 9   y              53940 non-null  float64
 10  z              53940 non-null  float64
 11  Quality-color  53940 non-null  object
dtypes: float64(6), int64(2), object(4)
memory usage: 4.9+ MB

In [9]:
# 6. summarize only 'object' columns of the diamonds
df.describe(include=['object'])

          cut  color clarity Quality-color
count   53940  53940   53940         53940
unique      5      7       8            35
top     Ideal      G     SI1      Ideal, G
freq    21551  11292   13065          4884

In [10]:
# 7. Rename two columns
df.rename(columns={'x':'X', 'y': 'Y'})
df

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z,Quality-color
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,"Ideal, E"
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,"Premium, E"
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,"Good, E"
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,"Premium, I"
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,"Good, J"
...,...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,"Ideal, D"
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,"Good, D"
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,"Very Good, D"
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,"Premium, H"
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,"Ideal, D"

In [11]:
# 8. rename all columns
df.rename(columns={'carat': 'Carat', 'Quality': 'Qlty', 'color': 'Color', 'clarity': 'Clarity', 'depth': 'Depth', 'table': 'Table', 'price': 'Price', 'X': 'x', 'Y':'y', 'z': 'z', 'Quality-color': 'Qlty-color'})

,Unnamed: 0,Carat,cut,Color,Clarity,Depth,Table,Price,x,y,z,Qlty-color
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,"Ideal, E"
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,"Premium, E"
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,"Good, E"
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,"Premium, I"
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,"Good, J"
...,...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,"Ideal, D"
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,"Good, D"
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,"Very Good, D"
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,"Premium, H"
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,"Ideal, D"

In [12]:
# 9. remove the 2nd column
df.drop(df.columns[1], axis=1)

,Unnamed: 0,cut,color,clarity,depth,table,price,x,y,z,Quality-color
0,1,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,"Ideal, E"
1,2,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,"Premium, E"
2,3,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,"Good, E"
3,4,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,"Premium, I"
4,5,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,"Good, J"
...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,"Ideal, D"
53936,53937,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,"Good, D"
53937,53938,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,"Very Good, D"
53938,53939,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,"Premium, H"
53939,53940,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,"Ideal, D"

In [13]:
# 10. delete multiple columns
df.drop(['cut', 'color'], axis=1)

,Unnamed: 0,carat,clarity,depth,table,price,x,y,z,Quality-color
0,1,0.23,SI2,61.5,55.0,326,3.95,3.98,2.43,"Ideal, E"
1,2,0.21,SI1,59.8,61.0,326,3.89,3.84,2.31,"Premium, E"
2,3,0.23,VS1,56.9,65.0,327,4.05,4.07,2.31,"Good, E"
3,4,0.29,VS2,62.4,58.0,334,4.20,4.23,2.63,"Premium, I"
4,5,0.31,SI2,63.3,58.0,335,4.34,4.35,2.75,"Good, J"
...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,SI1,60.8,57.0,2757,5.75,5.76,3.50,"Ideal, D"
53936,53937,0.72,SI1,63.1,55.0,2757,5.69,5.75,3.61,"Good, D"
53937,53938,0.70,SI1,62.8,60.0,2757,5.66,5.68,3.56,"Very Good, D"
53938,53939,0.86,SI2,61.0,58.0,2757,6.15,6.12,3.74,"Premium, H"
53939,53940,0.75,SI2,62.2,55.0,2757,5.83,5.87,3.64,"Ideal, D"

In [14]:
# 11. multiple rows deletion
df.drop([2,3],axis=0)

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z,Quality-color
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,"Ideal, E"
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,"Premium, E"
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,"Good, J"
5,6,0.24,Very Good,J,VVS2,62.8,57.0,336,3.94,3.96,2.48,"Very Good, J"
6,7,0.24,Very Good,I,VVS1,62.3,57.0,336,3.95,3.98,2.47,"Very Good, I"
...,...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,"Ideal, D"
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,"Good, D"
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,"Very Good, D"
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,"Premium, H"
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,"Ideal, D"

In [15]:
# 12. sort the cut series in ascending order
df.sort_values(by='cut')

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z,Quality-color
3850,3851,1.01,Fair,F,SI2,64.8,55.0,3477,6.37,6.26,4.10,"Fair, F"
51464,51465,1.20,Fair,G,I1,66.6,57.0,2376,6.57,6.50,4.34,"Fair, G"
51466,51467,0.90,Fair,G,SI2,65.4,57.0,2376,6.01,5.97,3.98,"Fair, G"
10237,10238,1.26,Fair,D,SI2,64.5,59.0,4746,6.75,6.71,4.34,"Fair, D"
10760,10761,1.01,Fair,E,SI1,69.5,55.0,4853,6.00,5.94,4.15,"Fair, E"
...,...,...,...,...,...,...,...,...,...,...,...,...
7402,7403,0.33,Very Good,G,VS2,62.8,54.0,579,4.40,4.42,2.77,"Very Good, G"
43101,43102,0.57,Very Good,E,SI2,58.8,57.3,1384,5.42,5.46,3.21,"Very Good, E"
16893,16894,1.00,Very Good,G,VS2,62.2,58.0,6743,6.35,6.39,3.96,"Very Good, G"
16898,16899,1.00,Very Good,D,VS2,59.6,60.0,6745,6.52,6.57,3.90,"Very Good, D"
21164,21165,1.00,Very Good,E,VVS2,61.7,55.0,9324,6.38,6.42,3.95,"Very Good, E"

In [16]:
# 13. to sort price series in descending order
df.sort_values(by='price',ascending=False)

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z,Quality-color
27749,27750,2.29,Premium,I,VS2,60.8,60.0,18823,8.50,8.47,5.16,"Premium, I"
27748,27749,2.00,Very Good,G,SI1,63.5,56.0,18818,7.90,7.97,5.04,"Very Good, G"
27747,27748,1.51,Ideal,G,IF,61.7,55.0,18806,7.37,7.41,4.56,"Ideal, G"
27746,27747,2.07,Ideal,G,SI2,62.5,55.0,18804,8.20,8.13,5.11,"Ideal, G"
27745,27746,2.00,Very Good,H,SI1,62.8,57.0,18803,7.95,8.00,5.01,"Very Good, H"
...,...,...,...,...,...,...,...,...,...,...,...,...
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,"Good, J"
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,"Premium, I"
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,"Good, E"
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,"Premium, E"
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,"Ideal, E"

In [17]:
# 14. sort the entire diamonds dataframe by the 'carat' series in ascending and descending order
df.sort_values(by='carat') # by ascending

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z,Quality-color
31593,31594,0.20,Premium,E,VS2,61.1,59.0,367,3.81,3.78,2.32,"Premium, E"
31597,31598,0.20,Ideal,D,VS2,61.5,57.0,367,3.81,3.77,2.33,"Ideal, D"
31596,31597,0.20,Premium,F,VS2,62.6,59.0,367,3.73,3.71,2.33,"Premium, F"
31595,31596,0.20,Ideal,E,VS2,59.7,55.0,367,3.86,3.84,2.30,"Ideal, E"
31594,31595,0.20,Premium,E,VS2,59.7,62.0,367,3.84,3.80,2.28,"Premium, E"
...,...,...,...,...,...,...,...,...,...,...,...,...
25999,26000,4.01,Premium,J,I1,62.5,62.0,15223,10.02,9.94,6.24,"Premium, J"
25998,25999,4.01,Premium,I,I1,61.0,61.0,15223,10.14,10.10,6.17,"Premium, I"
27130,27131,4.13,Fair,H,I1,64.8,61.0,17329,10.00,9.85,6.43,"Fair, H"
27630,27631,4.50,Fair,J,I1,65.8,58.0,18531,10.23,10.16,6.72,"Fair, J"
27415,27416,5.01,Fair,J,I1,65.5,59.0,18018,10.74,10.54,6.98,"Fair, J"

In [18]:
df.sort_values(by='carat',ascending=False)

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z,Quality-color
27415,27416,5.01,Fair,J,I1,65.5,59.0,18018,10.74,10.54,6.98,"Fair, J"
27630,27631,4.50,Fair,J,I1,65.8,58.0,18531,10.23,10.16,6.72,"Fair, J"
27130,27131,4.13,Fair,H,I1,64.8,61.0,17329,10.00,9.85,6.43,"Fair, H"
25999,26000,4.01,Premium,J,I1,62.5,62.0,15223,10.02,9.94,6.24,"Premium, J"
25998,25999,4.01,Premium,I,I1,61.0,61.0,15223,10.14,10.10,6.17,"Premium, I"
...,...,...,...,...,...,...,...,...,...,...,...,...
31592,31593,0.20,Premium,E,VS2,59.0,60.0,367,3.81,3.78,2.24,"Premium, E"
31591,31592,0.20,Premium,E,VS2,59.8,62.0,367,3.79,3.77,2.26,"Premium, E"
31601,31602,0.20,Premium,D,VS2,61.7,60.0,367,3.77,3.72,2.31,"Premium, D"
14,15,0.20,Premium,E,SI2,60.2,62.0,345,3.79,3.75,2.27,"Premium, E"
31596,31597,0.20,Premium,F,VS2,62.6,59.0,367,3.73,3.71,2.33,"Premium, F"

In [19]:
# 15.filter the dataframe to rows to only show carat weight at least 0.3
df[df['carat']>0.3]

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z,Quality-color
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,"Good, J"
13,14,0.31,Ideal,J,SI2,62.2,54.0,344,4.35,4.37,2.71,"Ideal, J"
15,16,0.32,Premium,E,I1,60.9,58.0,345,4.38,4.42,2.68,"Premium, E"
23,24,0.31,Very Good,J,SI1,59.4,62.0,353,4.39,4.43,2.62,"Very Good, J"
24,25,0.31,Very Good,J,SI1,58.1,62.0,353,4.44,4.47,2.59,"Very Good, J"
...,...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,"Ideal, D"
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,"Good, D"
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,"Very Good, D"
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,"Premium, H"
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,"Ideal, D"

In [20]:
# 16. convert python list to pandas series
lst = [1,2,3,4,5]
s1 = pd.Series(lst)
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [21]:
# 17. find details of diamond where len>5,width>5 and depth>5
df[(df.x>5) & (df.y>5) & (df.z>5)]

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z,Quality-color
11778,11779,1.83,Fair,J,I1,70.0,58.0,5083,7.34,7.28,5.12,"Fair, J"
13002,13003,2.14,Fair,J,I1,69.4,57.0,5405,7.74,7.70,5.36,"Fair, J"
13118,13119,2.15,Fair,J,I1,65.5,57.0,5430,8.01,7.95,5.23,"Fair, J"
13562,13563,1.96,Fair,F,I1,66.6,60.0,5554,7.59,7.56,5.04,"Fair, F"
13757,13758,2.22,Fair,J,I1,66.7,56.0,5607,8.04,8.02,5.36,"Fair, J"
...,...,...,...,...,...,...,...,...,...,...,...,...
27748,27749,2.00,Very Good,G,SI1,63.5,56.0,18818,7.90,7.97,5.04,"Very Good, G"
27749,27750,2.29,Premium,I,VS2,60.8,60.0,18823,8.50,8.47,5.16,"Premium, I"
48410,48411,0.51,Very Good,E,VS1,61.8,54.7,1970,5.12,5.15,31.80,"Very Good, E"
49189,49190,0.51,Ideal,E,VS1,61.8,55.0,2075,5.15,31.80,5.12,"Ideal, E"
49905,49906,0.50,Very Good,G,VVS1,63.7,58.0,2180,5.01,5.04,5.06,"Very Good, G"

In [23]:
# 18. display diamonds that are either premium or ideal
df[(df.cut=='Premium')| (df.cut=='Ideal')]

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z,Quality-color
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,"Ideal, E"
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,"Premium, E"
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,"Premium, I"
11,12,0.23,Ideal,J,VS1,62.8,56.0,340,3.93,3.90,2.46,"Ideal, J"
12,13,0.22,Premium,F,SI1,60.4,61.0,342,3.88,3.84,2.33,"Premium, F"
...,...,...,...,...,...,...,...,...,...,...,...,...
53931,53932,0.71,Premium,F,SI1,59.8,62.0,2756,5.74,5.73,3.43,"Premium, F"
53934,53935,0.72,Premium,D,SI1,62.7,59.0,2757,5.69,5.73,3.58,"Premium, D"
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,"Ideal, D"
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,"Premium, H"
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,"Ideal, D"

In [26]:
# 19. to find diamonds that are with a fair good or good or premium
df.loc[(df.cut == 'Fair')| (df.cut == 'Good')| (df.cut=='Premium')]

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z,Quality-color
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,"Premium, E"
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,"Good, E"
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,"Premium, I"
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,"Good, J"
8,9,0.22,Fair,E,VS2,65.1,61.0,337,3.87,3.78,2.49,"Fair, E"
...,...,...,...,...,...,...,...,...,...,...,...,...
53930,53931,0.71,Premium,E,SI1,60.5,55.0,2756,5.79,5.74,3.49,"Premium, E"
53931,53932,0.71,Premium,F,SI1,59.8,62.0,2756,5.74,5.73,3.43,"Premium, F"
53934,53935,0.72,Premium,D,SI1,62.7,59.0,2757,5.69,5.73,3.58,"Premium, D"
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,"Good, D"
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,"Premium, H"

In [27]:
# 20. All column labels of diamonds dataframe
df.columns

Index(['Unnamed: 0', 'carat', 'cut', 'color', 'clarity', 'depth', 'table',
       'price', 'x', 'y', 'z', 'Quality-color'],
      dtype='object')

In [28]:
# 21. read subset of 3 rows
subs = df.iloc[:3]
subs

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z,Quality-color
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,"Ideal, E"
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,"Premium, E"
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,"Good, E"

In [36]:
# 22. iterate through diamonds dataframe
randIndexes = np.random.randint(0, 5398, 50)
for i in randIndexes:
    print(df.loc[i], '\n')

Unnamed: 0          1685
carat               1.01
cut                 Good
color                  E
clarity               I1
depth               63.8
table               57.0
price               3032
x                    6.4
y                   6.33
z                   4.06
Quality-color    Good, E
Name: 1684, dtype: object

Unnamed: 0             3269
carat                  1.01
cut                 Premium
color                     I
clarity                 SI2
depth                  61.5
table                  62.0
price                  3360
x                      6.41
y                      6.37
z                      3.93
Quality-color    Premium, I
Name: 3268, dtype: object

Unnamed: 0              490
carat                  0.72
cut                 Premium
color                     E
clarity                 VS2
depth                  60.9
table                  60.0
price                  2822
x                       5.8
y                      5.76
z                      3.52
Quality-color    Premium, E
Name: 489, dtype: object

Unnamed: 0             5331
carat                  0.96
cut                 Premium
color                     I
clarity                 VS2
depth                  60.6
table                  60.0
price                  3808
x                      6.47
y                       6.4
z                       3.9
Quality-color    Premium, I
Name: 5330, dtype: object

Unnamed: 0          5067
carat                0.3
cut                 Good
color                  G
clarity              SI1
depth               63.8
table               56.0
price                574
x                    4.3
y                   4.26
z                   2.73
Quality-color    Good, G
Name: 5066, dtype: object

Unnamed: 0           2435
carat                0.76
cut                 Ideal
color                   G
clarity               VS2
depth                61.5
table                55.0
price                3183
x                    5.92
y                    5.88
z                    3.63
Quality-color    Ideal, G
Name: 2434, dtype: object

Unnamed: 0               1813
carat                    0.78
cut                 Very Good
color                       E
clarity                   SI1
depth                    60.9
table                    57.0
price                    3055
x                        5.93
y                        5.97
z                        3.62
Quality-color    Very Good, E
Name: 1812, dtype: object

Unnamed: 0           5110
carat                0.72
cut                 Ideal
color                   F
clarity               VS1
depth                61.4
table                56.0
price                3759
x                    5.75
y                    5.79
z                    3.54
Quality-color    Ideal, F
Name: 5109, dtype: object

Unnamed: 0           3704
carat                 1.0
cut                 Ideal
color                   E
clarity               SI2
depth                62.9
table                56.0
price                3450
x                    6.32
y                     6.3
z                    3.97
Quality-color    Ideal, E
Name: 3703, dtype: object

Unnamed: 0           5389
carat                 0.3
cut                 Ideal
color                   G
clarity               SI1
depth                62.8
table                56.0
price                 574
x                    4.32
y                    4.28
z                     2.7
Quality-color    Ideal, G
Name: 5388, dtype: object

Unnamed: 0           4155
carat                 0.9
cut                 Ideal
color                   H
clarity               SI2
depth                62.6
table                57.0
price                3548
x                    6.16
y                    6.07
z                    3.83
Quality-color    Ideal, H
Name: 4154, dtype: object

Unnamed: 0             3581
carat                  1.01
cut                 Premium
color                     J
clarity                 SI2
depth                  63.0
table                  60.0
price                  3421
x                      6.38
y                      6.31
z                       4.0
Quality-color    Premium, J
Name: 3580, dtype: object

Unnamed: 0          1713
carat                0.4
cut                 Good
color                  H
clarity              SI2
depth               63.7
table               59.0
price                561
x                   4.64
y                   4.69
z                   2.97
Quality-color    Good, H
Name: 1712, dtype: object

Unnamed: 0            640
carat                 0.8
cut                 Ideal
color                   I
clarity               VS1
depth                62.6
table                54.0
price                2842
x                    5.92
y                    5.96
z                    3.72
Quality-color    Ideal, I
Name: 639, dtype: object

Unnamed: 0            962
carat                0.71
cut                 Ideal
color                   F
clarity               VS2
depth                61.2
table                56.0
price                2891
x                    5.73
y                    5.77
z                    3.52
Quality-color    Ideal, F
Name: 961, dtype: object

Unnamed: 0             4150
carat                  0.91
cut                 Premium
color                     F
clarity                 SI2
depth                  58.9
table                  61.0
price                  3546
x                      6.36
y                      6.33
z                      3.74
Quality-color    Premium, F
Name: 4149, dtype: object

Unnamed: 0               1917
carat                     0.8
cut                 Very Good
color                       F
clarity                   SI1
depth                    63.5
table                    58.0
price                    3082
x                        5.89
y                        5.85
z                        3.73
Quality-color    Very Good, F
Name: 1916, dtype: object

Unnamed: 0           5245
carat                1.23
cut                 Ideal
color                   G
clarity               SI2
depth                61.6
table                55.0
price                3788
x                    6.91
y                    6.88
z                    4.25
Quality-color    Ideal, G
Name: 5244, dtype: object

Unnamed: 0           4736
carat                 0.3
cut                 Ideal
color                   F
clarity               VS2
depth                62.3
table                55.0
price                 573
x                     4.3
y                    4.34
z                    2.69
Quality-color    Ideal, F
Name: 4735, dtype: object

Unnamed: 0                602
carat                     0.7
cut                 Very Good
color                       E
clarity                   SI1
depth                    63.5
table                    59.0
price                    2838
x                        5.53
y                        5.49
z                         3.5
Quality-color    Very Good, E
Name: 601, dtype: object

Unnamed: 0               3970
carat                     0.9
cut                 Very Good
color                       E
clarity                   SI1
depth                    63.5
table                    55.0
price                    3508
x                        6.22
y                        6.12
z                        3.92
Quality-color    Very Good, E
Name: 3969, dtype: object

Unnamed: 0               2671
carat                    0.91
cut                 Very Good
color                       G
clarity                   SI2
depth                    62.0
table                    59.0
price                    3238
x                        6.19
y                        6.22
z                        3.85
Quality-color    Very Good, G
Name: 2670, dtype: object

Unnamed: 0             1910
carat                  0.82
cut                 Premium
color                     F
clarity                 SI1
depth                  61.1
table                  60.0
price                  3080
x                      6.02
y                      5.96
z                      3.66
Quality-color    Premium, F
Name: 1909, dtype: object

Unnamed: 0           1390
carat                0.24
cut                 Ideal
color                   G
clarity              VVS1
depth                62.2
table                56.0
price                 559
x                     4.0
y                    4.04
z                     2.5
Quality-color    Ideal, G
Name: 1389, dtype: object

Unnamed: 0           3409
carat                 0.3
cut                 Ideal
color                   F
clarity               VS2
depth                60.3
table                57.0
price                 568
x                    4.34
y                    4.39
z                    2.63
Quality-color    Ideal, F
Name: 3408, dtype: object

Unnamed: 0          4435
carat                0.9
cut                 Good
color                  G
clarity              SI1
depth               64.5
table               57.0
price               3615
x                   6.04
y                   6.09
z                   3.91
Quality-color    Good, G
Name: 4434, dtype: object

Unnamed: 0             3192
carat                  0.78
cut                 Premium
color                     F
clarity                 VS1
depth                  60.6
table                  57.0
price                  3342
x                       6.0
y                      5.95
z                      3.62
Quality-color    Premium, F
Name: 3191, dtype: object

Unnamed: 0           1807
carat                0.79
cut                 Ideal
color                   E
clarity               SI1
depth                62.1
table                54.0
price                3053
x                    5.96
y                    5.92
z                    3.69
Quality-color    Ideal, E
Name: 1806, dtype: object

Unnamed: 0           1436
carat                0.82
cut                 Ideal
color                   F
clarity               SI1
depth                62.6
table                57.0
price                2974
x                    5.96
y                    6.02
z                    3.75
Quality-color    Ideal, F
Name: 1435, dtype: object

Unnamed: 0           1703
carat                0.78
cut                 Ideal
color                   D
clarity               SI1
depth                62.4
table                57.0
price                3035
x                    5.87
y                    5.89
z                    3.67
Quality-color    Ideal, D
Name: 1702, dtype: object

Unnamed: 0           404
carat               0.32
cut                 Good
color                  I
clarity              SI1
depth               63.9
table               55.0
price                554
x                   4.36
y                   4.34
z                   2.78
Quality-color    Good, I
Name: 403, dtype: object

Unnamed: 0           3124
carat                0.96
cut                 Ideal
color                   J
clarity               VS2
depth                61.5
table                57.0
price                3326
x                    6.32
y                    6.36
z                     3.9
Quality-color    Ideal, J
Name: 3123, dtype: object

Unnamed: 0               3824
carat                     0.8
cut                 Very Good
color                       F
clarity                   VS2
depth                    62.1
table                    60.0
price                    3471
x                        5.86
y                        5.92
z                        3.66
Quality-color    Very Good, F
Name: 3823, dtype: object

Unnamed: 0           4160
carat                1.09
cut                 Ideal
color                   G
clarity                I1
depth                61.0
table                56.0
price                3549
x                    6.62
y                    6.66
z                    4.05
Quality-color    Ideal, G
Name: 4159, dtype: object

Unnamed: 0          1038
carat               0.95
cut                 Good
color                  I
clarity              SI2
depth               63.8
table               57.0
price               2905
x                   6.23
y                   6.13
z                   3.94
Quality-color    Good, I
Name: 1037, dtype: object

Unnamed: 0               5304
carat                    1.01
cut                 Very Good
color                       E
clarity                   SI2
depth                    63.4
table                    58.0
price                    3801
x                        6.43
y                        6.34
z                        4.05
Quality-color    Very Good, E
Name: 5303, dtype: object

Unnamed: 0                  8
carat                    0.26
cut                 Very Good
color                       H
clarity                   SI1
depth                    61.9
table                    55.0
price                     337
x                        4.07
y                        4.11
z                        2.53
Quality-color    Very Good, H
Name: 7, dtype: object

Unnamed: 0            607
carat                0.71
cut                 Ideal
color                   F
clarity               VS1
depth                61.5
table                57.0
price                2839
x                    5.74
y                    5.71
z                    3.52
Quality-color    Ideal, F
Name: 606, dtype: object

Unnamed: 0          4786
carat                1.0
cut                 Good
color                  E
clarity              SI2
depth               57.7
table               65.0
price               3696
x                   6.55
y                   6.59
z                   3.79
Quality-color    Good, E
Name: 4785, dtype: object

Unnamed: 0               2007
carat                     0.9
cut                 Very Good
color                       J
clarity                   VS1
depth                    62.6
table                    55.0
price                    3102
x                        6.11
y                        6.13
z                        3.83
Quality-color    Very Good, J
Name: 2006, dtype: object

Unnamed: 0               1986
carat                     0.7
cut                 Very Good
color                       E
clarity                   VS1
depth                    63.4
table                    57.0
price                    3095
x                        5.63
y                        5.67
z                        3.58
Quality-color    Very Good, E
Name: 1985, dtype: object

Unnamed: 0             4129
carat                  1.52
cut                 Premium
color                     I
clarity                  I1
depth                  61.2
table                  58.0
price                  3541
x                      7.43
y                      7.35
z                      4.52
Quality-color    Premium, I
Name: 4128, dtype: object

Unnamed: 0               5280
carat                     0.9
cut                 Very Good
color                       D
clarity                   SI2
depth                    62.5
table                    58.0
price                    3798
x                        6.12
y                        6.16
z                        3.84
Quality-color    Very Good, D
Name: 5279, dtype: object

Unnamed: 0           130
carat               0.91
cut                 Fair
color                  H
clarity              SI2
depth               65.7
table               60.0
price               2763
x                   6.03
y                   5.99
z                   3.95
Quality-color    Fair, H
Name: 129, dtype: object

Unnamed: 0           1578
carat                0.71
cut                 Ideal
color                   G
clarity               SI1
depth                61.6
table                55.0
price                3007
x                    5.72
y                    5.78
z                    3.54
Quality-color    Ideal, G
Name: 1577, dtype: object

Unnamed: 0              753
carat                  0.77
cut                 Premium
color                     F
clarity                 SI1
depth                  61.0
table                  58.0
price                  2856
x                      5.94
y                       5.9
z                      3.61
Quality-color    Premium, F
Name: 752, dtype: object

Unnamed: 0          5359
carat               1.05
cut                 Fair
color                  D
clarity              SI2
depth               65.4
table               59.0
price               3816
x                    6.3
y                   6.24
z                    4.1
Quality-color    Fair, D
Name: 5358, dtype: object

Unnamed: 0             3212
carat                   0.7
cut                 Premium
color                     F
clarity                VVS1
depth                  61.8
table                  60.0
price                  3348
x                      5.67
y                      5.63
z                      3.49
Quality-color    Premium, F
Name: 3211, dtype: object

Unnamed: 0            576
carat                 0.8
cut                 Ideal
color                   G
clarity               VS2
depth                62.2
table                56.0
price                2834
x                    5.94
y                    5.87
z                    3.67
Quality-color    Ideal, G
Name: 575, dtype: object

Unnamed: 0           3685
carat                0.81
cut                 Ideal
color                   H
clarity               SI1
depth                61.4
table                56.0
price                3446
x                     6.0
y                    6.05
z                     3.7
Quality-color    Ideal, H
Name: 3684, dtype: object

In [37]:
# 23. drop all non-numeric columns
df_numeric = df.select_dtypes(include=['number'])
df_numeric

       Unnamed: 0  carat  depth  table  price     x     y     z
0               1   0.23   61.5   55.0    326  3.95  3.98  2.43
1               2   0.21   59.8   61.0    326  3.89  3.84  2.31
2               3   0.23   56.9   65.0    327  4.05  4.07  2.31
3               4   0.29   62.4   58.0    334  4.20  4.23  2.63
4               5   0.31   63.3   58.0    335  4.34  4.35  2.75
...           ...    ...    ...    ...    ...   ...   ...   ...
53935       53936   0.72   60.8   57.0   2757  5.75  5.76  3.50
53936       53937   0.72   63.1   55.0   2757  5.69  5.75  3.61
53937       53938   0.70   62.8   60.0   2757  5.66  5.68  3.56
53938       53939   0.86   61.0   58.0   2757  6.15  6.12  3.74
53939       53940   0.75   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 8 columns]

In [38]:
# 24.include only numeric columns
df_numeric

       Unnamed: 0  carat  depth  table  price     x     y     z
0               1   0.23   61.5   55.0    326  3.95  3.98  2.43
1               2   0.21   59.8   61.0    326  3.89  3.84  2.31
2               3   0.23   56.9   65.0    327  4.05  4.07  2.31
3               4   0.29   62.4   58.0    334  4.20  4.23  2.63
4               5   0.31   63.3   58.0    335  4.34  4.35  2.75
...           ...    ...    ...    ...    ...   ...   ...   ...
53935       53936   0.72   60.8   57.0   2757  5.75  5.76  3.50
53936       53937   0.72   63.1   55.0   2757  5.69  5.75  3.61
53937       53938   0.70   62.8   60.0   2757  5.66  5.68  3.56
53938       53939   0.86   61.0   58.0   2757  6.15  6.12  3.74
53939       53940   0.75   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 8 columns]

In [ ]:
# 25. pass a list of data types to only describe certain types of diamonds df